call plug#begin('~/.config/nvim/plugged')
" basic
Plug 'tpope/vim-repeat'
" smart
Plug 'SirVer/ultisnips'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': 'yes \| ./install' } " :FZF
Plug 'junegunn/fzf.vim' " adds more commands
Plug 'tpope/vim-fugitive' " alarmingly feature-rich
Plug 'airblade/vim-gitgutter' " also alarmingly feature-rich
Plug 'benekastah/neomake' " ft-specific makeprgs like simpatico, shellcheck
" testing
Plug 'rking/ag.vim' " `brew install the_silver_searcher`
Plug 'tpope/vim-sleuth' " auto-detect indent settings
Plug 'AndrewRadev/sideways.vim' " moving parameters around
" nav
Plug 'Lokaltog/vim-easymotion'
Plug 'christoomey/vim-tmux-navigator'
" edit
Plug 'junegunn/vim-easy-align'
Plug 'tpope/vim-surround'
Plug 'gibiansky/vim-latex-objects'
Plug 'tpope/vim-commentary'
" colorschemes
Plug 'vim-scripts/ScrollColors' " for testing colorschemes
Plug 'frankier/neovim-colors-solarized-truecolor-only'
Plug 'penicolas/simplon.vim'
Plug 'romainl/Apprentice'
Plug 'jpo/vim-railscasts-theme'
Plug 'chriskempson/base16-vim'
" misc
Plug 'junegunn/rainbow_parentheses.vim'
Plug 'keith/swift.vim'
Plug 'qpkorr/vim-bufkill'
call plug#end()

" basics
filetype plugin indent on
syntax on
set hlsearch " highlight search results
set incsearch " start searching while typing search
set ignorecase " required for smartcase: searches are case-insensitive
set smartcase " ignore case if search pattern is all lowercase, otherwise case-sensitive
set number " line numbers
set showcmd " show normal command while typing

" colorscheme
set termguicolors
" colorscheme base16-flat
colorscheme apprentice
set bg=dark
" minor QoL for quickfix
hi Search ctermfg=8 ctermbg=3 guifg=#95A5A6 guibg=yellow
" bright yellow line number
hi clear CursorLine
hi CursorLineNr term=bold ctermfg=14 gui=bold guifg=Yellow
set cursorline

" indenting: largely obsoleted by sleuth (I'm still testing it)
" set softtabstop=4
" set tabstop=8 " apparently non-8 can get breaky (see :he 'tabstop')
" set shiftwidth=4
" set smarttab " insert tabs on the start of a line according to shiftwidth, not tabstop

" mouse
set mouse=ni " enabled, normal and insert mode only

" misc
set backspace=indent,eol,start	" backspace behaves like Word
set virtualedit=all		" let the cursor go in 'invalid' places
set hidden			" enable loading a buffer in a window that already has a modified buffer
set wildignore=*.swp,*.sqo,*.bak,*.pyc,*.class " ignore these filetypes when completing with <Tab>
set wildmenu			" enhanced command-line completion
"set ttimeoutlen=50		" fix delay leaving insert mode esp in airline: is this needed in nvim?
set formatoptions+=j		" join comment lines without the comment prefix
set updatetime=750		" delay until CursorHold event. extra I/O

inoremap <C-e> <C-o><C-e>
inoremap <C-y> <C-o><C-y>

" leader
let mapleader = "\\"
nnoremap <leader><space> :nohlsearch<CR>
nnoremap <leader>w :w<CR>
nnoremap <leader>c :setl bufhidden=delete<CR>:bnext<CR>
nnoremap <leader>p "+p
nnoremap <leader>P "+P
nnoremap <leader>y "+y
vnoremap <leader>y "+y
nnoremap <leader>e :e ~/dotfiles/nvim/init.vim<CR>
nnoremap <leader>v :v/^\s*[#\n]/p<CR>

" toggle rainbow parentheses
nnoremap <leader>r :RainbowParentheses!!<CR>

" <C-Tab> and <C-S-Tab> to change buffers
" iTerm2 must be configured to send these on <C-Tab> and <C-S-Tab>. I hate terminals
set <F13>^=[1;2P
set <F14>^=[1;2Q
nmap <silent><F13> :bn<CR>
nmap <silent><F14> :bp<CR>
" this 'should' work in nvim, but I think iTerm isn't configured right
" nmap <C-Tab> :bn<CR>
" nmap <C-S-Tab> :bp<CR>
" make it insert mode too
imap <silent><F13> <C-o>:bn<CR>
imap <silent><F14> <C-o>:bp<CR>

" Where to put the window for vim-plug
let g:plug_window = 'topleft new'

" Airline: currently doesn't init quite right (look at top & bottom before &
" after switching to a new buffer)
let g:airline_theme = 'base16'
set laststatus=2 	" always show it
set noshowmode		" don't show '--INSERT--' etc: redundant
let g:airline_powerline_fonts = 1 " use special chars in special font
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#show_buffers = 1 " display buffers with a single tab
let g:airline#extensions#whitespace#enabled = 0

" EasyMotion
map <Leader>l <Plug>(easymotion-lineforward)
map <Leader>j <Plug>(easymotion-j)
map <Leader>k <Plug>(easymotion-k)
map <Leader>h <Plug>(easymotion-linebackward)
nmap s <Plug>(easymotion-s)
let g:EasyMotion_startofline = 0 " keep cursor column when JK motion
let g:EasyMotion_smartcase = 1 " type l, match l & L

"" YouCompleteMe, UltiSnips (some overlap)
let g:ycm_confirm_extra_conf = 0 " automatically load .ycm_extra_conf.py files
let g:ycm_global_ycm_extra_conf = '~/.config/nvim/.ycm_extra_conf.py'

" Together:
" http://stackoverflow.com/questions/14896327/ultisnips-and-youcompleteme
" make YCM compatible with UltiSnips (using supertab)
let g:ycm_key_list_select_completion = ['<C-n>', '<Down>']
let g:ycm_key_list_previous_completion = ['<C-p>', '<Up>']
let g:SuperTabDefaultCompletionType = '<C-n>'
" better key bindings for UltiSnipsExpandTrigger
let g:UltiSnipsExpandTrigger = "<Tab>"
let g:UltiSnipsJumpForwardTrigger = "<Tab>"
let g:UltiSnipsJumpBackwardTrigger = "<S-Tab>"

let g:plug_window='' " defaults to 'vertical topleft new' but I'd rather it used the same window

" quick window navigation
" if <C-h> doesn't work, update neovim - it used to be caused by: https://github.com/neovim/neovim/issues/2048 
:nnoremap <C-h> <C-w>h
:nnoremap <C-j> <C-w>j
:nnoremap <C-k> <C-w>k
:nnoremap <C-l> <C-w>l

" Start interactive EasyAlign in visual mode (e.g. vip<Enter>)
vmap <Enter> <Plug>(EasyAlign)

" Start interactive EasyAlign for a motion/text object (e.g. gaip)
nmap ga <Plug>(EasyAlign)

" style marking: justin rules
" autocmd! BufEnter,WinEnter *.styled call matchadd("SpecialComment", "^\[[A-Za-z\-]*\].*$", -1)
" autocmd! BufEnter,WinEnter *.styled syn match cComment "^\[[A-Za-z\-]*\].*$"

" fzf.vim: quickselect files
imap <c-x><c-f> <plug>(fzf-complete-path)
nnoremap <leader><tab> :FZF<CR>

" vim-bufkill (ie <C-w> c without killing the window too)
nnoremap <C-c> :BD<cr>


nmap <leader>b :SidewaysLeft<CR>
nmap <leader>n :SidewaysRight<CR>
